# Generated by Django 3.1.4 on 2021-01-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='buttonlink',
            field=models.TextField(default='', max_length=255),
        ),
    ]
