# Generated by Django 3.1.6 on 2021-03-12 04:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_team_yt_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Richaboutus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('richeditor', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
