# Generated by Django 3.1.7 on 2021-05-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_richaboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headandfoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbyuser', models.CharField(max_length=255)),
                ('numberbyuser', models.CharField(max_length=255)),
                ('instalink', models.CharField(max_length=255)),
                ('facebooklink', models.CharField(max_length=255)),
                ('twitterlink', models.CharField(max_length=255)),
                ('youtuberlink', models.CharField(max_length=255)),
            ],
        ),
    ]
