# Generated by Django 3.1.7 on 2021-05-08 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_headandfoot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headandfoot',
            old_name='youtuberlink',
            new_name='youtubelink',
        ),
    ]
