# Generated by Django 3.1.7 on 2021-05-24 12:00

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='age',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('canon', 'canon'), ('nikon', 'nikon'), ('sony', 'sony'), ('red', 'red'), ('fuzi', 'fuzi'), ('panasonic', 'panasonic'), ('other', 'other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('code', 'code'), ('product reviews', 'product reviews'), ('vlogs', 'vlogs'), ('comedy', 'comedy'), ('gaming', 'gaming'), ('film making', 'film making'), ('cooking', 'cooking'), ('inspiration', 'inspiration'), ('tricks and hacks', 'tricks and hacks'), ('education', 'education'), ('artist', 'artist'), ('news', 'news'), ('acting', 'acting'), ('unboxing', 'unboxing'), ('health and fitness', 'health and fitness'), ('philosophy', 'philosophy'), ('psychology', 'psychology'), ('spirituality', 'spirituality')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 24, 17, 30, 26, 458907)),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('solo', 'solo'), ('small', 'small'), ('large', 'large')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
