# Generated by Django 3.1.7 on 2021-06-04 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('socialaccount', '0003_extra_data_default_dict'),
        ('account', '0002_email_max_length'),
        ('youtubers', '0004_auto_20210526_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuber',
            name='slug',
            field=models.SlugField(default='myslug'),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 4, 20, 32, 4, 698440)),
        ),
        migrations.DeleteModel(
            name='YoutuberUpdateForm',
        ),
    ]
