# Generated by Django 3.1.7 on 2021-06-04 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0005_auto_20210604_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 4, 20, 33, 18, 369250)),
        ),
    ]
