# Generated by Django 3.1.7 on 2021-06-04 15:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtubers', '0007_auto_20210604_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtuber',
            name='slug',
        ),
        migrations.AddField(
            model_name='youtuber',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 4, 21, 5, 58, 801152)),
        ),
    ]
