# Generated by Django 3.1.7 on 2021-06-10 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0009_auto_20210610_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytresponsemodel',
            name='user',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 16, 12, 12, 255570)),
        ),
        migrations.AlterField(
            model_name='ytresponsemodel',
            name='ytmsg',
            field=models.CharField(default='', max_length=50),
        ),
    ]
