# Generated by Django 3.1.7 on 2021-06-04 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiretuber',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 4, 20, 32, 4, 663573)),
        ),
    ]
